name: Generate Test Documents

on: [push]
  # pull_request:
  #   branches:
  #     - develop
  #   types: [closed]

jobs:
  generate-test-documents:
    runs-on: ubuntu-18.04
    container:
      image: phpdoc/phpdoc
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v1
      - run: git checkout develop
      - run: git branch
      - run: phpdoc
      - run: docker run --rm -v $(pwd):/data phpdoc/phpdoc run -d /data/src/tests -t /data/docs/tests