name: Generate Test Documents

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  generate-test-documents:
    runs-on: ubuntu-18.04
    container:
      image: phpdoc/phpdoc
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v1
      - run: |
          pwd
          ls -la
          phpdoc/phpdoc -h
          phpdoc/phpdoc run -d /data/src/tests -t /data/docs/tests