name: Generate Test Documents

on: [push]
  # pull_request:
  #   branches:
  #     - develop
  #   types: [closed]

jobs:
  generate-test-documents:
    runs-on: ubuntu-18.04
    container:
      image: phpdoc/phpdoc
    # if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop
      - name: Git Settings
        run: |
          git config --local user.email test@example.com
          git config --local user.name test_user
      - name: Generate Documents
        run: phpdoc run -d ./src/tests -t ./docs/tests
      - name: Commit
        run: |
            git add .
            git commit -m 'docs: テスト仕様書生成'