name: Generate Test Documents

on:
  pull_request:
    branches:
      - develop
    paths:
      - "src/tests/**"
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate-test-documents:
    runs-on: ubuntu-18.04
    container:
      image: phpdoc/phpdoc
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: develop
      - name: Settings
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --local user.email "example-inc@users.noreply.github.com"
          git config --local user.name "example-inc"
      - name: Generate
        run: phpdoc run --config ./phpdoc.xml
      - name: Commit
        run: |
            git add .
            git commit -m 'docs: テスト仕様書生成'
            git pull
            git push origin develop
